import assert from 'node:assert/strict';
import { buildMissionPrompt } from '../generation.js';
import { assertGeminiPayloadWithinBudget, MAX_GEMINI_INPUT_TOKENS, estimateGeminiInputTokens } from '../gemini.js';

const hugeExcerpt = 'FACT_B FACT_C raw fetched page text '.repeat(40000);
const evidence = [{ id: 'ev-001', title: 'Official result', url: 'https://treasury.gov/report', domain: 'treasury.gov', snippet: 'Exact SearXNG one-line result about FACT_A only.', excerpt: hugeExcerpt, sourceQuality: { tier: 'primary', score: 95, flags: [] }, relevance: { target: true, agenda: true }, fetchStatus: 'ok', hasUsableContent: true }];
const point = { id: 'pp-001', rank: 1, rankScore: 99, target: 'China', claim: 'FACT_A: China has an official debt transparency commitment relevant to restructuring.', evidenceExcerpt: hugeExcerpt, evidenceIds: ['ev-001'], usableForGeneration: true, scores: { agendaRelevance: 90 } };
const missionState = { portfolioCountry: 'Indonesia', oppositionCountries: [{ name: 'China', iso: 'CHN' }], targetMode: 'selected_global', totalPois: 5, aggression: 90, controversy: 90, diplomacy: 30, length: 60, poiTypes: ['AUTO'], backgroundGuideFile: { name: 'guide.pdf', mimeType: 'application/pdf', base64: 'AAAA' }, freezeDate: '2026-08-15' };
const prompt = buildMissionPrompt({ form: { committee: 'ECOFIN', agenda: 'debt restructuring', portfolio: 'Indonesia' }, sliders: missionState, selectedTargets: missionState.oppositionCountries, targetingMode: 'selected_global', includeFollowUp: false, poiCount: 5, missionState, researchPacket: { evidence, availableVerifiedPressurePoints: [point] }, rankedCandidatePool: [point] });
assert.match(prompt, /BACKGROUND GUIDE/);
assert.match(prompt, /native Gemini inlineData file\/document input/);
assert.match(prompt, /FACT_A/);
assert.match(prompt, /https:\/\/treasury.gov\/report/);
assert.match(prompt, /Exact SearXNG one-line result about FACT_A only\./);
assert.doesNotMatch(prompt, /FACT_B/);
assert.doesNotMatch(prompt, /FACT_C/);
assert.doesNotMatch(prompt, /raw fetched page text/);
assert.ok(!prompt.includes(JSON.stringify(evidence)), 'full research packet impossible in compact prompt');
assert.ok(estimateGeminiInputTokens(JSON.stringify({ evidence })) > MAX_GEMINI_INPUT_TOKENS, 'old full-packet path would be oversized');
assert.doesNotThrow(() => assertGeminiPayloadWithinBudget({ contents: [{ role: 'user', parts: [{ text: prompt }, { inlineData: { mimeType: 'application/pdf', data: 'AAAA' } }] }] }, { requestContext: { operation: 'compact-331k-regression' } }), 'compact request remains local-budget safe');
console.log('compact payload regression tests passed');
