import http from 'node:http';
import dns from 'node:dns/promises';
import net from 'node:net';

const PORT = Number(process.env.RESEARCH_PROXY_PORT || 8787);
const BASE = process.env.SEARXNG_BASE_URL;
const MAX_QUERIES = 12, MAX_RESULTS = 10, MAX_URLS = 10, MAX_DOCUMENT_CHARS = 6000, MAX_BYTES = 1_500_000, TIMEOUT_MS = 12000, REDIRECTS = 3;
const searchCache = new Map(); const fetchCache = new Map();
const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'POST,OPTIONS', 'access-control-allow-headers': 'content-type' }); res.end(JSON.stringify(body)); };
const readBody = (req) => new Promise((resolve, reject) => { let body=''; req.on('data', c => { body += c; if (body.length > 100_000) reject(new Error('request-too-large')); }); req.on('end', () => { try { resolve(JSON.parse(body || '{}')); } catch { reject(new Error('invalid-json')); } }); req.on('error', reject); });
const normQuery = (q) => String(q || '').replace(/https?:\/\/\S+/gi, '').replace(/\s+/g, ' ').trim().slice(0, 220);
const dedupe = (items, keyFn = (x) => x) => { const seen = new Set(); return items.filter((x) => { const k = keyFn(x); if (!k || seen.has(k)) return false; seen.add(k); return true; }); };
function normalizedResult(r, query) { const url = r.url || r.link || ''; if (!/^https?:\/\//i.test(url)) return null; return { title: String(r.title || '').trim(), url, snippet: String(r.content || r.snippet || '').trim(), engine: String(r.engine || r.engines?.[0] || '').trim(), query }; }
function ipBlocked(ip) { if (!ip) return true; if (ip === '::1' || ip === '0:0:0:0:0:0:0:1') return true; if (ip.startsWith('fe80:') || ip.startsWith('fc') || ip.startsWith('fd')) return true; if (ip === '169.254.169.254') return true; if (net.isIPv4(ip)) { const [a,b] = ip.split('.').map(Number); return a === 10 || a === 127 || (a === 192 && b === 168) || (a === 172 && b >= 16 && b <= 31) || (a === 169 && b === 254) || a === 0; } return false; }
async function safeUrl(raw) { const u = new URL(raw); if (!['http:', 'https:'].includes(u.protocol)) throw new Error('blocked-url-scheme'); const host = u.hostname.toLowerCase(); if (['localhost', 'metadata.google.internal'].includes(host) || host.endsWith('.localhost')) throw new Error('blocked-internal-host'); const addrs = await dns.lookup(host, { all: true }); if (!addrs.length || addrs.some((a) => ipBlocked(a.address))) throw new Error('blocked-private-address'); return u; }
async function fetchLimited(url, redirects = 0) { const u = await safeUrl(url); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), TIMEOUT_MS); try { const res = await fetch(u, { redirect: 'manual', signal: controller.signal, headers: { 'user-agent': 'ChitForgeResearchProxy/1.0' } }); if ([301,302,303,307,308].includes(res.status)) { if (redirects >= REDIRECTS) throw new Error('too-many-redirects'); const loc = res.headers.get('location'); if (!loc) throw new Error('redirect-without-location'); return fetchLimited(new URL(loc, u).toString(), redirects + 1); } const type = res.headers.get('content-type') || ''; if (!res.ok) throw new Error(`http-${res.status}`); const reader = res.body.getReader(); let chunks=[], size=0; while (true) { const { done, value } = await reader.read(); if (done) break; size += value.byteLength; if (size > MAX_BYTES) throw new Error('response-too-large'); chunks.push(value); } return { url: res.url || u.toString(), type, html: new TextDecoder().decode(Buffer.concat(chunks)) }; } finally { clearTimeout(timer); } }
const cleanText = (html) => String(html || '').replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/\s+/g, ' ').trim();
const meta = (html, name) => new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']+)`, 'i').exec(html)?.[1] || '';
function extractDoc(url, html) { const title = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.replace(/\s+/g, ' ').trim() || ''; const text = cleanText(html).slice(0, MAX_DOCUMENT_CHARS); const publishedAt = meta(html, 'article:published_time') || meta(html, 'date') || meta(html, 'citation_publication_date') || null; return { url, title, text, publishedAt, fetchStatus: text.length >= 120 ? 'ok' : 'failed' }; }
async function handleSearch(req, res) { if (!BASE) return json(res, 503, { category: 'searxng-unavailable', message: 'SearXNG unavailable: SEARXNG_BASE_URL is not configured.' }); const body = await readBody(req); const queries = dedupe((body.queries || []).map(normQuery).filter(Boolean).slice(0, MAX_QUERIES), (q) => q.toLowerCase()); const maxResultsPerQuery = Math.min(MAX_RESULTS, Math.max(1, Number(body.maxResultsPerQuery) || 8)); if (!queries.length) return json(res, 400, { category: 'invalid-request', message: 'queries must contain at least one query.' }); const all = []; for (const query of queries) { const key = JSON.stringify({ query, maxResultsPerQuery }); if (searchCache.has(key)) { all.push(...searchCache.get(key)); continue; } const u = new URL('/search', BASE); u.searchParams.set('q', query); u.searchParams.set('format', 'json'); const r = await fetch(u, { signal: AbortSignal.timeout(TIMEOUT_MS), headers: { accept: 'application/json' } }).catch((cause) => { throw new Error(`SearXNG unavailable: ${cause.message}`); }); if (!r.ok) throw new Error(`SearXNG unavailable: HTTP ${r.status}`); const p = await r.json(); const results = (p.results || []).slice(0, maxResultsPerQuery).map((x) => normalizedResult(x, query)).filter(Boolean); searchCache.set(key, results); all.push(...results); } return json(res, 200, { results: dedupe(all, (r) => { try { const u = new URL(r.url); u.hash=''; return u.toString(); } catch { return r.url; } }) }); }
async function handleFetch(req, res) { const body = await readBody(req); const urls = dedupe((body.urls || []).filter((u) => /^https?:\/\//i.test(String(u))).slice(0, MAX_URLS)); if (!urls.length) return json(res, 400, { category: 'invalid-request', message: 'urls must contain at least one http(s) URL.' }); const documents = []; for (const url of urls) { if (fetchCache.has(url)) { documents.push(fetchCache.get(url)); continue; } let doc; try { const fetched = await fetchLimited(url); doc = extractDoc(fetched.url, fetched.html); } catch (e) { doc = { url, title: '', text: '', publishedAt: null, fetchStatus: 'failed', error: e.message }; } fetchCache.set(url, doc); documents.push(doc); } return json(res, 200, { documents }); }
const server = http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return json(res, 204, {}); try { if (req.method === 'POST' && req.url === '/research/search') return await handleSearch(req, res); if (req.method === 'POST' && req.url === '/research/fetch') return await handleFetch(req, res); return json(res, 404, { category: 'not-found', message: 'Not found.' }); } catch (e) { return json(res, /SearXNG unavailable/.test(e.message) ? 502 : 500, { category: /SearXNG unavailable/.test(e.message) ? 'searxng-unavailable' : 'research-proxy-unavailable', message: e.message }); } });
server.listen(PORT, () => console.log(`Research proxy listening on http://localhost:${PORT}`));
